#ifndef COMPUT_GLOBALS_H
#define COMPUT_GLOBALS_H

#include <SDL.h>

namespace comput {

#define COMPUT_SDL_INIT_LIST \
  SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_TIMER | SDL_INIT_EVENTS

#define COMPUT_SIMULATION_DEFAULT_TIMESTEP 0.01

#define COMPUT_WINDOW_DEFAULT_W 640
#define COMPUT_WINDOW_DEFAULT_H 480
#define COMPUT_WINDOW_DEFAULT_FLAGS 0

#define COMPUT_RENDERER_DEFAULT_INDEX 1
#define COMPUT_RENDERER_DEFAULT_FLAGS 0

}  // namespace comput

#endif
